= SELinux =

== Expected functionality ==

Essentially provide mechanisms to manage local customizations:

* Set enforcing/permissive
* restorecon portions of filesystem tree
* Set/Get Booleans
* Set/Get file contexts
* Manage logins
* Manage ports

== Available modules ==

=== Core modules ===

https://github.com/ansible/ansible-modules-core

selinux::
Configures the SELinux mode and policy.

seboolean::
Toggles SELinux booleans.


=== Extras modules ===

https://github.com/ansible/ansible-modules-extras

sefcontext::
Manages SELinux file context mapping definitions Similar to the `semanage fcontext` command.
Currently it doesn't work due to https://bugzilla.redhat.com/show_bug.cgi?id=1405110

seport::
Manages SELinux network port type definitions.

=== Modules provided by this repository ===

selogin::
Manages linux user to SELinux user mapping

== Usage ==

----
vars:
  ...
roles:
  - SELinux
----

=== SELinux role ===

This role can be configured using variables as it is described bellow.

==== set SELinux mode permanently and in running system ====

----
SELinux_type: targeted
SELinux_mode: enforcing
SELinux_change_running: 1
----

==== set SELinux booleans ====

----
SELinux_booleans:
  - { name: 'samba_enable_home_dirs', state: 'on' }
  - { name: 'ssh_sysadm_login', state: 'on', persistent: 'yes' }
----

==== Set SELinux file contexts ====

----
SELinux_file_contexts:
  - { target: '/tmp/test_dir(/.*)?', setype: 'user_home_dir_t', ftype: 'd' }
----

Note: it doesn't work right now due to https://bugzilla.redhat.com/show_bug.cgi?id=1405110

==== run restorecon on filesystem trees ====

----
SELinux_restore_dirs:
  - /tmp/test_dir
----

==== Set linux user to SELinux user mapping ====

----
    SELinux_logins:
      - { login: 'plautrba', seuser: 'staff_u', state: 'absent' }
      - { login: '__default__', seuser: 'staff_u', serange: 's0-s0:c0.c1023', state: 'present' }
----
