#!/bin/bash

set -e
set -x

prepare() {
  # install qemu because its post install script sets up /dev/kvm
  sudo apt-get install -y qemu-system-x86

  sudo chmod a+rw /dev/kvm

  docker-cache restore
}

run() {
  make check CACHEDIR=$SEMAPHORE_CACHE_DIR

  docker-cache snapshot
}

"$@"
