#!/bin/bash

set -e
set -x

prepare() {
  # install qemu because its post install script sets up /dev/kvm
  sudo apt-get update
  sudo apt-get install -q -y qemu-system-x86

  sudo chmod a+rw /dev/kvm

  docker-cache restore
}

run() {
  set -o pipefail
  make check CACHEDIR=$SEMAPHORE_CACHE_DIR | tee
  set +o pipefail

  docker-cache snapshot
}

"$@"
